insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Morganica Harlock', 'Golf Course', '2020-10-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Augusto Gherardini', 'Crowley', '2012-10-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sheilah Layson', 'Cambridge', '2011-01-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harri March', 'Luster', '1982-12-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jeffy Stainbridge', 'Dwight', '2013-05-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nehemiah Sheeres', 'Jana', '1996-07-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brice Philcock', 'Declaration', '1992-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fabian Glyde', 'Waubesa', '1983-03-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Charissa Ord', 'Lien', '1995-08-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Godwin Epinoy', 'Pepper Wood', '2006-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Georgette Bowskill', 'Maywood', '2018-07-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rochell Landon', 'Bay', '2007-03-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leontine Hobble', 'Birchwood', '1986-07-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Terra Alldridge', 'Lake View', '1989-03-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Correna Iggo', 'Hayes', '2002-09-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lon Sainsberry', 'Victoria', '1986-10-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Prescott Weber', 'Northwestern', '1989-12-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Claudius Grief', 'Sullivan', '2001-02-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alberta Caldero', 'Vermont', '1986-05-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jeanne Swetland', '4th', '2016-10-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Warde De Bernardis', '1st', '2012-10-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Zuzana Ramshaw', 'Towne', '2017-04-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sigismond Wink', 'Burning Wood', '1987-03-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kristian Burras', 'Glacier Hill', '2004-07-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garret Gladdish', 'Meadow Ridge', '1982-08-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Giusto Butting', 'Arrowood', '2003-10-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Curcio Seer', 'Kingsford', '2011-04-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jewelle Pilbury', 'Prairie Rose', '2002-01-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ryann Goodwyn', 'Roth', '1996-06-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hillard Stennet', '6th', '2009-05-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nomi Sieghard', 'Milwaukee', '2012-08-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aeriell Bartholomaus', 'Evergreen', '2013-10-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Penelopa Hartley', 'Merrick', '1981-11-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harlie Gligorijevic', 'Moland', '2019-12-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jolene Yerson', 'Green Ridge', '2007-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ynes Einchcombe', 'Russell', '2019-09-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marianna Gittose', 'Clemons', '1986-11-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tobiah Thrasher', 'Hazelcrest', '2014-03-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Skipton Ferretti', 'Dayton', '2019-04-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Edna Jereatt', 'International', '1993-01-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Buddie Grzegorzewicz', 'Hallows', '1983-06-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Teddi Villa', 'Del Sol', '1992-07-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Janella Conisbee', 'Dahle', '1991-10-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Julita Mansion', 'Holy Cross', '2013-02-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Loralyn Lorait', 'Mallory', '1988-05-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Isidoro Osmant', 'Ruskin', '2017-03-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Stearn Feldhuhn', 'Melvin', '1994-12-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Selestina Bray', 'Mcguire', '1983-02-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fairfax Conaghan', 'Norway Maple', '2007-06-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Asa Gilchriest', 'Farwell', '1996-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bernete Pasby', 'Sutherland', '2003-09-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Olin Fursse', 'Eagan', '2003-03-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ewan Laws', 'Morning', '2011-05-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sadella Morrilly', 'Bluejay', '1988-04-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bernadine Longina', 'Dennis', '2019-02-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hanna Cleary', 'Loeprich', '1985-03-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Goran Wasbrough', 'Arrowood', '1993-11-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kate Paydon', 'Warbler', '1986-06-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jemimah Jolliss', 'Magdeline', '2008-10-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kaleb Farra', 'Melby', '1987-09-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Baron Witham', 'Corry', '2009-06-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Simonne Fearnyough', 'Westerfield', '1985-08-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Loreen Pressdee', 'Darwin', '1992-11-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nealon Voas', 'Clarendon', '2018-02-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cloris Leathem', 'Darwin', '1998-08-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Amalia Zaple', 'Coolidge', '2007-10-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Anet Atkins', 'Fulton', '2018-03-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cam Lambillion', 'Farragut', '2015-05-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Granville Upwood', 'Monica', '1982-06-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Deloris Brumpton', 'Acker', '2008-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rosene Jovanovic', 'Del Mar', '2014-12-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Burg Aldous', 'Sullivan', '1979-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Agosto Mapston', 'Blaine', '2012-09-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bord Shepley', 'Bunker Hill', '1982-04-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ana Blum', 'Nevada', '2001-03-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pammie Ogles', 'American Ash', '2010-03-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rosemary Preene', 'Miller', '2008-01-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arnaldo Mishaw', 'Heath', '2005-04-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dorree Cabrera', 'Dakota', '1980-08-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kassey Winskill', 'Sullivan', '1996-11-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jasmin Casaro', 'Westridge', '2005-10-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eveleen Ivankov', 'Hallows', '1992-07-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alvinia Gatchel', 'Superior', '1993-06-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Allie Paddock', 'North', '2013-05-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Happy Accomb', 'Spenser', '1993-03-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dill Madill', 'Fallview', '1985-09-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ainslee Yushmanov', 'Boyd', '1986-06-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tallie Shave', 'Ramsey', '1984-05-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thatch Morden', 'Melody', '1980-01-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Saree Atthow', 'Mariners Cove', '1984-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shannah Laydel', 'Eastwood', '1995-05-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elbertine Welman', 'Oak', '2020-11-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Andrea Meritt', 'Crownhardt', '1993-12-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jacquelin Cianelli', 'Haas', '2014-04-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alethea Becraft', 'Muir', '1993-10-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aprilette Woolard', 'Nevada', '1984-11-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jessi Galfour', 'Sutherland', '2004-02-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Esma Porson', 'Arizona', '1986-11-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Henka Abrahmovici', 'Loftsgordon', '2005-04-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Isac Huett', 'Vahlen', '2005-03-24');
