insert into tren (modelo, capacidad) values ('Land Cruiser', 1);
insert into tren (modelo, capacidad) values ('350Z', 2);
insert into tren (modelo, capacidad) values ('Continental', 3);
insert into tren (modelo, capacidad) values ('Skylark', 4);
insert into tren (modelo, capacidad) values ('E-Class', 5);
insert into tren (modelo, capacidad) values ('Malibu', 6);
insert into tren (modelo, capacidad) values ('LeSabre', 7);
insert into tren (modelo, capacidad) values ('XL7', 8);
insert into tren (modelo, capacidad) values ('Aspire', 9);
insert into tren (modelo, capacidad) values ('G-Series G30', 10);
insert into tren (modelo, capacidad) values ('Bonneville', 11);
insert into tren (modelo, capacidad) values ('Brat', 12);
insert into tren (modelo, capacidad) values ('Town & Country', 13);
insert into tren (modelo, capacidad) values ('Sonata', 14);
insert into tren (modelo, capacidad) values ('400SE', 15);
insert into tren (modelo, capacidad) values ('Catera', 16);
insert into tren (modelo, capacidad) values ('Grand Prix', 17);
insert into tren (modelo, capacidad) values ('Fortwo', 18);
insert into tren (modelo, capacidad) values ('88', 19);
insert into tren (modelo, capacidad) values ('Escalade', 20);
insert into tren (modelo, capacidad) values ('Navigator', 21);
insert into tren (modelo, capacidad) values ('Mohave/Borrego', 22);
insert into tren (modelo, capacidad) values ('Explorer', 23);
insert into tren (modelo, capacidad) values ('Altima', 24);
insert into tren (modelo, capacidad) values ('Galant', 25);
insert into tren (modelo, capacidad) values ('Camaro', 26);
insert into tren (modelo, capacidad) values ('Mystique', 27);
insert into tren (modelo, capacidad) values ('Sunfire', 28);
insert into tren (modelo, capacidad) values ('Mirage', 29);
insert into tren (modelo, capacidad) values ('Sierra 3500', 30);
insert into tren (modelo, capacidad) values ('G37', 31);
insert into tren (modelo, capacidad) values ('Z3', 32);
insert into tren (modelo, capacidad) values ('S80', 33);
insert into tren (modelo, capacidad) values ('MP4-12C', 34);
insert into tren (modelo, capacidad) values ('Grand Am', 35);
insert into tren (modelo, capacidad) values ('M', 36);
insert into tren (modelo, capacidad) values ('A7', 37);
insert into tren (modelo, capacidad) values ('Grand Marquis', 38);
insert into tren (modelo, capacidad) values ('Dakota', 39);
insert into tren (modelo, capacidad) values ('Silverado 2500', 40);
insert into tren (modelo, capacidad) values ('Tacoma Xtra', 41);
insert into tren (modelo, capacidad) values ('MDX', 42);
insert into tren (modelo, capacidad) values ('7 Series', 43);
insert into tren (modelo, capacidad) values ('B-Series', 44);
insert into tren (modelo, capacidad) values ('NSX', 45);
insert into tren (modelo, capacidad) values ('Sunbird', 46);
insert into tren (modelo, capacidad) values ('850', 47);
insert into tren (modelo, capacidad) values ('Avalon', 48);
insert into tren (modelo, capacidad) values ('Clubman', 49);
insert into tren (modelo, capacidad) values ('Grand Marquis', 50);
insert into tren (modelo, capacidad) values ('PT Cruiser', 51);
insert into tren (modelo, capacidad) values ('Previa', 52);
insert into tren (modelo, capacidad) values ('Camaro', 53);
insert into tren (modelo, capacidad) values ('Elantra', 54);
insert into tren (modelo, capacidad) values ('Boxster', 55);
insert into tren (modelo, capacidad) values ('Grand Prix', 56);
insert into tren (modelo, capacidad) values ('Tacoma Xtra', 57);
insert into tren (modelo, capacidad) values ('LX', 58);
insert into tren (modelo, capacidad) values ('Safari', 59);
insert into tren (modelo, capacidad) values ('Sorento', 60);
insert into tren (modelo, capacidad) values ('Rio', 61);
insert into tren (modelo, capacidad) values ('C-Class', 62);
insert into tren (modelo, capacidad) values ('Silverado', 63);
insert into tren (modelo, capacidad) values ('Pathfinder', 64);
insert into tren (modelo, capacidad) values ('TSX', 65);
insert into tren (modelo, capacidad) values ('RX-8', 66);
insert into tren (modelo, capacidad) values ('Golf', 67);
insert into tren (modelo, capacidad) values ('Continental', 68);
insert into tren (modelo, capacidad) values ('Corvette', 69);
insert into tren (modelo, capacidad) values ('Camaro', 70);
insert into tren (modelo, capacidad) values ('1500 Club Coupe', 71);
insert into tren (modelo, capacidad) values ('Montero', 72);
insert into tren (modelo, capacidad) values ('Vision', 73);
insert into tren (modelo, capacidad) values ('Grand Marquis', 74);
insert into tren (modelo, capacidad) values ('TL', 75);
insert into tren (modelo, capacidad) values ('Escort', 76);
insert into tren (modelo, capacidad) values ('Legacy', 77);
insert into tren (modelo, capacidad) values ('Grand Prix', 78);
insert into tren (modelo, capacidad) values ('F-Series Super Duty', 79);
insert into tren (modelo, capacidad) values ('Corvette', 80);
insert into tren (modelo, capacidad) values ('Silverado', 81);
insert into tren (modelo, capacidad) values ('M', 82);
insert into tren (modelo, capacidad) values ('911', 83);
insert into tren (modelo, capacidad) values ('Sorento', 84);
insert into tren (modelo, capacidad) values ('B-Series Plus', 85);
insert into tren (modelo, capacidad) values ('RL', 86);
insert into tren (modelo, capacidad) values ('Bronco', 87);
insert into tren (modelo, capacidad) values ('Aurora', 88);
insert into tren (modelo, capacidad) values ('Mustang', 89);
insert into tren (modelo, capacidad) values ('Firebird', 90);
insert into tren (modelo, capacidad) values ('T100', 91);
insert into tren (modelo, capacidad) values ('S90', 92);
insert into tren (modelo, capacidad) values ('Wrangler', 93);
insert into tren (modelo, capacidad) values ('MX-6', 94);
insert into tren (modelo, capacidad) values ('Outlander', 95);
insert into tren (modelo, capacidad) values ('Mariner', 96);
insert into tren (modelo, capacidad) values ('Prelude', 97);
insert into tren (modelo, capacidad) values ('W201', 98);
insert into tren (modelo, capacidad) values ('Supra', 99);
insert into tren (modelo, capacidad) values ('1500', 100);
